global:
  edition: ce
  hosts:
    domain: 192.168.56.111.nip.io
    https: false
  ingress:
    configureCertmanager: false
    class: "gitlab-nginx"  # Cambiado de "traefik" a "gitlab-nginx"
    enabled: true
    useGlobalIngress: false
  
certmanager:
  install: false
prometheus:
  install: false
  
gitlab-runner:
  install: true
  
resources:
  requests:
    cpu: 300m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

postgresql:
  persistence:
    size: 1Gi
    
redis:
  master:
    persistence:
      size: 1Gi
      
minio:
  persistence:
    size: 1Gi