# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  config.vm.synced_folder "../.", "/vagrant", mount_options: ["dmode=775", "fmode=664"], type: "virtualbox"
  config.vm.network "private_network", ip: "192.168.56.111", virtualbox__intnet: true, name: "mynetwork"
  config.vm.network "forwarded_port", guest: 9999, host: 9999, protocol: "tcp"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "bonus-gitlab"
    vb.memory = 3072
    vb.cpus = 1
    vb.gui = true
    vb.customize ["modifyvm", :id, "--nic2", "intnet"]
    vb.customize ["modifyvm", :id, "--intnet2", "mynetwork"]
  end
end