Vagrant.configure("2") do |config|

    config.vm.box = "generic/alpine317"
  
    config.vm.provider "virtualbox" do |virtualbox|
      virtualbox.memory = 1024
      virtualbox.cpus = 1
      virtualbox.gui = true
      virtualbox.customize ["modifyvm", :id, "--nic2", "intnet"]
      virtualbox.customize ["modifyvm", :id, "--intnet2", "mynetwork"]
    end
  
    config.vm.define "imonteroS" do |server|
      server.vm.hostname = "imonteroS"
      server.vm.network "private_network", ip: "192.168.56.110", virtualbox__intnet: true, name: "mynetwork"
      server.vm.network "forwarded_port", guest: 80, host: 8080
      server.vm.synced_folder ".", "/vagrant"
      server.vm.provision "shell", privileged: true, path: "config/configserver.sh", args: ["192.168.56.110"]
    end
  end