

Vagrant.configure("2") do | config |
    config.vm.provider "virtualbox" do | vb |
    vb.cpus = 4
    vb.memory = 4096
  end
  
    config.vm.define "bonus" do |gitlab|
  	    gitlab.vm.network "forwarded_port", guest: 9999, host: 9999, protocol: "tcp"
        gitlab.vm.box = "debian/bullseye64"
        gitlab.vm.hostname = "bonus"
        gitlab.vm.network "private_network", ip: "192.168.56.111"
        gitlab.vm.provision "shell", inline: <<-SHELL
            sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config

            useradd -m -s /bin/bash iot
            
            echo "iot:iot" | chpasswd
            
            echo "iot ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/iot
            chmod 0440 /etc/sudoers.d/iot
            
            mkdir -p /home/iot/.ssh
            cp /home/vagrant/.ssh/authorized_keys /home/iot/.ssh/
            chown -R iot:iot /home/iot/.ssh
            chmod 700 /home/iot/.ssh
            chmod 600 /home/iot/.ssh/authorized_keys
            sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
            service ssh restart
        SHELL
        gitlab.vm.provision "shell", path: "scripts/gitlab_setup.sh", env: {"HOST_IP" => "#{ENV['HOST_IP']}"}
    end
end