Vagrant.configure("2") do |config|
    config.vm.box = "generic/alpine317"
  
    config.vm.provider "virtualbox" do |virtualbox|
      virtualbox.memory = 1024
      virtualbox.cpus = 1
    end
  
    config.vm.define "imonteroS" do |server|
      server.vm.hostname = "imonteroS"
      server.vm.network "private_network", ip: "192.168.56.110"
      server.vm.synced_folder ".", "/vagrant"
      server.vm.provision "shell", privileged: true, path: "config/server.sh", args: ["192.168.56.110"]
    end
  
    config.vm.define "imonteroSW" do |worker|
      worker.vm.hostname = "imonteroSW"
      worker.vm.network "private_network", ip: "192.168.56.111"
      worker.vm.synced_folder ".", "/vagrant"
      worker.vm.provision "shell", privileged: true, path: "config/worker.sh", args: ["192.168.56.110", "192.168.56.111"]
    end
  end