# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian12"
    config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=775", "fmode=664"], type: "virtualbox"

    config.vm.hostname = "k3d-argocd"

    config.vm.network "private_network", ip: "192.168.56.110", virtualbox__intnet: true, name: "mynetwork"

    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.network "forwarded_port", guest: 8888, host: 8888
    config.vm.network "forwarded_port", guest: 80, host: 8081
    
    config.vm.provider "virtualbox" do |vb|
      vb.name = "k3d-argocd"
      vb.memory = 2048
      vb.cpus = 2
      vb.gui = true
      vb.customize ["modifyvm", :id, "--nic2", "intnet"]
      vb.customize ["modifyvm", :id, "--intnet2", "mynetwork"]
    end
  end
