# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'io/console'

print "Introduce password for user 'iot': "
iot_password = STDIN.noecho(&:gets).chomp
puts "" 

Vagrant.configure("2") do |config|
  # VM GitLab
  config.vm.define "gitlab" do |gitlab|
    gitlab.vm.box = "debian/bullseye64"
    gitlab.vm.hostname = "gitlab"
    gitlab.vm.network "private_network", ip: "192.168.56.111"
    gitlab.vm.network "forwarded_port", guest: 9999, host: 9999, protocol: "tcp"
    
    gitlab.vm.provider "virtualbox" do |vb|
      vb.name = "bonus-gitlab"
      vb.memory = 4096
      vb.cpus = 4
    end
    
    gitlab.vm.provision "shell", inline: <<-SHELL
      sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
      useradd -m -s /bin/bash iot
      echo "iot:#{iot_password}" | chpasswd
      echo "iot ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/iot
      chmod 0440 /etc/sudoers.d/iot
      mkdir -p /home/iot/.ssh
      cp /home/vagrant/.ssh/authorized_keys /home/iot/.ssh/
      chown -R iot:iot /home/iot/.ssh
      chmod 700 /home/iot/.ssh
      chmod 600 /home/iot/.ssh/authorized_keys
      sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
      service ssh restart
    SHELL
    
    gitlab.vm.provision "shell", path: "scripts/gitlab_setup.sh", env: {"HOST_IP" => "192.168.56.111"}
  end

  # VM  K3d and Argo CD
  config.vm.define "argocd" do |argocd|
    argocd.vm.box = "debian/bullseye64"
    argocd.vm.hostname = "bonus-k3d-argocd"
    argocd.vm.network "private_network", ip: "192.168.56.112"
    
    argocd.vm.network "forwarded_port", guest: 8080, host: 8080
    argocd.vm.network "forwarded_port", guest: 8888, host: 8888
    argocd.vm.network "forwarded_port", guest: 80, host: 8081
    
    argocd.vm.provider "virtualbox" do |vb|
      vb.name = "bonus-k3d-argocd"
      vb.memory = 2048
      vb.cpus = 2
    end
    
    argocd.vm.provision "shell", inline: <<-SHELL
      sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
      useradd -m -s /bin/bash iot
      echo "iot:#{iot_password}" | chpasswd
      echo "iot ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/iot
      chmod 0440 /etc/sudoers.d/iot
      mkdir -p /home/iot/.ssh
      cp /home/vagrant/.ssh/authorized_keys /home/iot/.ssh/
      chown -R iot:iot /home/iot/.ssh
      chmod 700 /home/iot/.ssh
      chmod 600 /home/iot/.ssh/authorized_keys
      systemctl restart sshd
    SHELL
    
  end
end