# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  
  config.vm.hostname = "k3d-gitlab"
  
  config.vm.network "private_network", ip: "192.168.56.111"
  
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8888, host: 8888
  config.vm.network "forwarded_port", guest: 80, host: 8081
  config.vm.network "forwarded_port", guest: 443, host: 8443

  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "k3d-gitlab"
    vb.memory = 4096
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    
    useradd -m -s /bin/bash iot
    
    echo "iot:iot" | chpasswd
    
    echo "iot ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/iot
    chmod 0440 /etc/sudoers.d/iot
    
    mkdir -p /home/iot/.ssh
    cp /home/vagrant/.ssh/authorized_keys /home/iot/.ssh/
    chown -R iot:iot /home/iot/.ssh
    chmod 700 /home/iot/.ssh
    chmod 600 /home/iot/.ssh/authorized_keys
    
    systemctl restart sshd
  SHELL
end